version: '3'
services:
  app:
    image: yelghom/dvna:latest  
    ports:
      - "3000:3000"
    environment:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }} 
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }} 
      POSTGRES_DB: dvna-tp2  
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    depends_on:
      - db
    restart: always

  db:
    image: postgres:13  
    environment:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

volumes:
  pgdata:
