version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB: dvna-tp2
      POSTGRES_USER: ayahfarhat
      POSTGRES_PASSWORD: Postgres1
      DATABASE_URL: postgres://ayahfarhat:Postgres1@db:5432/dvna-tp2
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: dvna-tp2
      POSTGRES_USER: ayahfarhat
      POSTGRES_PASSWORD: Postgres1
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
