name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  security_tests:
    name: Security Testing
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run OWASP ZAP Scan
      run: |
        docker run --rm -v $(pwd):/zap/wrk/:rw -t ictu/zap2docker-weekly zap-baseline.py -I -j -t http://localhost:3000/ -r testreport.html 

    # - name: Run SonarQube Scan
    #   env:
    #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    #   run: |
    #     sonar-scanner \
    #     -Dsonar.projectKey=your_project_key \
    #     -Dsonar.sources=. \
    #     -Dsonar.host.url=https://your-sonarqube-url

    # - name: Run CodeQL Analysis
    #   uses: github/codeql-action/init@v2
    #   with:
    #     languages: javascript
    #     queries: security-extended
